import type { ExamSession, Registration, Score, Venue, WorkVersion, TimelineEvent } from '@/types'
import { checkJumpLevelEligibility, createTimelineEvent, isBorderlineScore, getScoreResult } from '@/types'

export const seedVenues: Venue[] = [
  {
    id: 'venue-1',
    name: '主考场A',
    address: '市文化中心一楼101室',
    capacity: 50,
    equipment: ['书画桌', '毛毡', '笔墨纸砚', '照明系统']
  },
  {
    id: 'venue-2',
    name: '主考场B',
    address: '市文化中心一楼102室',
    capacity: 30,
    equipment: ['书画桌', '毛毡', '笔墨纸砚', '照明系统']
  },
  {
    id: 'venue-3',
    name: '备用考场',
    address: '市文化中心二楼201室',
    capacity: 20,
    equipment: ['书画桌', '毛毡', '笔墨纸砚', '照明系统', '空调']
  },
]

const venue1 = seedVenues[0]
const venue2 = seedVenues[1]
const venue3 = seedVenues[2]

export const seedSessions: ExamSession[] = [
  {
    id: 'session-3',
    level: 3,
    levelCategory: '初级',
    examDate: '2026-07-15',
    examTime: '09:00',
    maxSlots: 50,
    registeredCount: 1,
    waitlistSlots: 10,
    waitlistCount: 0,
    fee: 200,
    status: 'open',
    venueId: venue1.id,
    venue: venue1,
    createdBy: '考点管理员',
    createdAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'session-5',
    level: 5,
    levelCategory: '中级',
    examDate: '2026-07-20',
    examTime: '14:00',
    maxSlots: 30,
    registeredCount: 2,
    waitlistSlots: 5,
    waitlistCount: 1,
    fee: 300,
    status: 'open',
    venueId: venue2.id,
    venue: venue2,
    createdBy: '考点管理员',
    createdAt: '2026-06-01T10:05:00Z',
  },
  {
    id: 'session-8',
    level: 8,
    levelCategory: '高级',
    examDate: '2026-07-25',
    examTime: '09:00',
    maxSlots: 20,
    registeredCount: 1,
    waitlistSlots: 3,
    waitlistCount: 0,
    fee: 500,
    status: 'open',
    venueId: venue3.id,
    venue: venue3,
    createdBy: '考点管理员',
    createdAt: '2026-06-01T10:10:00Z',
  },
  {
    id: 'session-4',
    level: 4,
    levelCategory: '中级',
    examDate: '2026-07-18',
    examTime: '10:00',
    maxSlots: 40,
    registeredCount: 0,
    waitlistSlots: 8,
    waitlistCount: 0,
    fee: 250,
    status: 'open',
    venueId: venue1.id,
    venue: venue1,
    createdBy: '考点管理员',
    createdAt: '2026-06-02T09:00:00Z',
  },
]

const createWorkVersions = (count: number): WorkVersion[] => {
  return Array.from({ length: count }, (_, i) => ({
    id: `work-version-${i + 1}`,
    version: i + 1,
    workImageBase64: '',
    uploadedAt: `2026-06-${10 + i}T14:${30 + i * 5}:00Z`,
    uploadNote: i === 0 ? '首次上传作品' : `修改后重传 v${i + 1}`,
  }))
}

const createTimeline = (events: Array<{type: TimelineEvent['type']; title: string; description: string; time: string}>): TimelineEvent[] => {
  return events.map(e => ({
    id: `event-${Math.random().toString(36).substr(2, 9)}`,
    type: e.type,
    title: e.title,
    description: e.description,
    timestamp: e.time,
  }))
}

export const seedRegistrations: Registration[] = [
  {
    id: 'reg-1',
    sessionId: 'session-5',
    candidateName: '张三',
    candidatePhone: '13800001111',
    appliedLevel: 5,
    passedLevel: 3,
    jumpLevelCheck: checkJumpLevelEligibility(5, 3),
    workVersions: createWorkVersions(2),
    currentWorkVersion: 2,
    workUploaded: true,
    workImageBase64: '',
    paid: true,
    paidAmount: 300,
    paidAt: '2026-06-10T14:30:00Z',
    status: 'paid',
    canWithdraw: true,
    waitlistEntry: null,
    reassignment: null,
    timeline: createTimeline([
      { type: 'register', title: '提交报名', description: '张三 提交了 5 级考试报名', time: '2026-06-10T10:00:00Z' },
      { type: 'upload', title: '上传作品 v1', description: '首次上传作品', time: '2026-06-10T11:00:00Z' },
      { type: 'upload', title: '上传作品 v2', description: '修改后重传 v2', time: '2026-06-10T14:20:00Z' },
      { type: 'payment', title: '缴费完成', description: '已缴纳报名费 ¥300', time: '2026-06-10T14:30:00Z' },
    ]),
    createdAt: '2026-06-10T10:00:00Z',
  },
  {
    id: 'reg-2',
    sessionId: 'session-5',
    candidateName: '李四',
    candidatePhone: '13800002222',
    appliedLevel: 5,
    passedLevel: 1,
    jumpLevelCheck: checkJumpLevelEligibility(5, 1),
    workVersions: [],
    currentWorkVersion: 0,
    workUploaded: false,
    workImageBase64: '',
    paid: false,
    paidAmount: 0,
    paidAt: '',
    status: 'pending_upload',
    canWithdraw: true,
    waitlistEntry: null,
    reassignment: null,
    timeline: createTimeline([
      { type: 'register', title: '提交报名', description: '李四 提交了 5 级考试报名', time: '2026-06-11T09:00:00Z' },
      { type: 'register', title: '跳级待审核', description: '跨4级报考，需提供证明材料', time: '2026-06-11T09:00:01Z' },
    ]),
    createdAt: '2026-06-11T09:00:00Z',
  },
  {
    id: 'reg-3',
    sessionId: 'session-8',
    candidateName: '王五',
    candidatePhone: '13800003333',
    appliedLevel: 8,
    passedLevel: 6,
    jumpLevelCheck: checkJumpLevelEligibility(8, 6),
    workVersions: createWorkVersions(1),
    currentWorkVersion: 1,
    workUploaded: true,
    workImageBase64: '',
    paid: false,
    paidAmount: 0,
    paidAt: '',
    status: 'pending_payment',
    canWithdraw: true,
    waitlistEntry: null,
    reassignment: null,
    timeline: createTimeline([
      { type: 'register', title: '提交报名', description: '王五 提交了 8 级考试报名', time: '2026-06-12T15:00:00Z' },
      { type: 'upload', title: '上传作品 v1', description: '首次上传作品', time: '2026-06-12T16:00:00Z' },
    ]),
    createdAt: '2026-06-12T15:00:00Z',
  },
  {
    id: 'reg-4',
    sessionId: 'session-5',
    candidateName: '赵六',
    candidatePhone: '13800004444',
    appliedLevel: 5,
    passedLevel: 3,
    jumpLevelCheck: checkJumpLevelEligibility(5, 3),
    workVersions: createWorkVersions(1),
    currentWorkVersion: 1,
    workUploaded: true,
    workImageBase64: '',
    paid: true,
    paidAmount: 300,
    paidAt: '2026-06-13T10:00:00Z',
    status: 'waitlist',
    canWithdraw: true,
    waitlistEntry: {
      id: 'waitlist-1',
      registrationId: 'reg-4',
      position: 1,
      joinedAt: '2026-06-13T10:05:00Z',
      expiresAt: '2026-06-20T10:05:00Z',
    },
    reassignment: null,
    timeline: createTimeline([
      { type: 'register', title: '提交报名', description: '赵六 提交了 5 级考试报名', time: '2026-06-13T09:30:00Z' },
      { type: 'upload', title: '上传作品 v1', description: '首次上传作品', time: '2026-06-13T09:45:00Z' },
      { type: 'payment', title: '缴费完成', description: '已缴纳报名费 ¥300', time: '2026-06-13T10:00:00Z' },
      { type: 'waitlist', title: '加入候补队列', description: '当前候补位次：第 1 位', time: '2026-06-13T10:05:00Z' },
    ]),
    createdAt: '2026-06-13T09:30:00Z',
  },
  {
    id: 'reg-5',
    sessionId: 'session-3',
    candidateName: '钱七',
    candidatePhone: '13800005555',
    appliedLevel: 3,
    passedLevel: 0,
    jumpLevelCheck: checkJumpLevelEligibility(3, 0),
    workVersions: createWorkVersions(3),
    currentWorkVersion: 3,
    workUploaded: true,
    workImageBase64: '',
    paid: true,
    paidAmount: 200,
    paidAt: '2026-06-14T09:00:00Z',
    status: 'pending_reassign',
    canWithdraw: true,
    waitlistEntry: null,
    reassignment: {
      id: 'reassign-1',
      registrationId: 'reg-5',
      oldSessionId: 'session-3',
      newSessionId: null,
      reason: '原场地设备维修，临时调整考场',
      feeDifference: 0,
      status: 'pending',
      createdAt: '2026-06-15T14:00:00Z',
    },
    timeline: createTimeline([
      { type: 'register', title: '提交报名', description: '钱七 提交了 3 级考试报名', time: '2026-06-14T08:00:00Z' },
      { type: 'upload', title: '上传作品 v1', description: '首次上传作品', time: '2026-06-14T08:30:00Z' },
      { type: 'upload', title: '上传作品 v2', description: '修改后重传 v2', time: '2026-06-14T08:45:00Z' },
      { type: 'upload', title: '上传作品 v3', description: '最终版本 v3', time: '2026-06-14T08:55:00Z' },
      { type: 'payment', title: '缴费完成', description: '已缴纳报名费 ¥200', time: '2026-06-14T09:00:00Z' },
      { type: 'reassign', title: '场地调整待改派', description: '原场地设备维修，临时调整考场', time: '2026-06-15T14:00:00Z' },
    ]),
    createdAt: '2026-06-14T08:00:00Z',
  },
  {
    id: 'reg-6',
    sessionId: 'session-3',
    candidateName: '孙八',
    candidatePhone: '13800006666',
    appliedLevel: 3,
    passedLevel: 1,
    jumpLevelCheck: checkJumpLevelEligibility(3, 1),
    workVersions: createWorkVersions(1),
    currentWorkVersion: 1,
    workUploaded: true,
    workImageBase64: '',
    paid: true,
    paidAmount: 200,
    paidAt: '2026-06-14T11:00:00Z',
    status: 'pending_review',
    canWithdraw: true,
    waitlistEntry: null,
    reassignment: null,
    timeline: createTimeline([
      { type: 'register', title: '提交报名', description: '孙八 提交了 3 级考试报名', time: '2026-06-14T10:00:00Z' },
      { type: 'upload', title: '上传作品 v1', description: '首次上传作品', time: '2026-06-14T10:30:00Z' },
      { type: 'payment', title: '缴费完成', description: '已缴纳报名费 ¥200', time: '2026-06-14T11:00:00Z' },
      { type: 'score', title: '成绩录入（临界线）', description: '初评分数：61分，高于合格线1分，属于临界区间，需复核', time: '2026-06-15T16:00:00Z' },
    ]),
    createdAt: '2026-06-14T10:00:00Z',
  },
  {
    id: 'reg-7',
    sessionId: 'session-3',
    candidateName: '周九',
    candidatePhone: '13800007777',
    appliedLevel: 3,
    passedLevel: 0,
    jumpLevelCheck: checkJumpLevelEligibility(3, 0),
    workVersions: createWorkVersions(1),
    currentWorkVersion: 1,
    workUploaded: true,
    workImageBase64: '',
    paid: true,
    paidAmount: 200,
    paidAt: '2026-06-14T13:00:00Z',
    status: 'scored',
    canWithdraw: true,
    waitlistEntry: null,
    reassignment: null,
    timeline: createTimeline([
      { type: 'register', title: '提交报名', description: '周九 提交了 3 级考试报名', time: '2026-06-14T12:00:00Z' },
      { type: 'upload', title: '上传作品 v1', description: '首次上传作品', time: '2026-06-14T12:30:00Z' },
      { type: 'payment', title: '缴费完成', description: '已缴纳报名费 ¥200', time: '2026-06-14T13:00:00Z' },
      { type: 'score', title: '成绩录入', description: '初评分数：85分，结果：良好', time: '2026-06-15T15:00:00Z' },
    ]),
    createdAt: '2026-06-14T12:00:00Z',
  },
]

const borderlineScore = 61
const normalScore = 85

export const seedScores: Score[] = [
  {
    id: 'score-1',
    registrationId: 'reg-6',
    sessionId: 'session-3',
    candidateName: '孙八',
    appliedLevel: 3,
    judgeName: '李评委',
    score: borderlineScore,
    isBorderline: isBorderlineScore(borderlineScore).isBorderline,
    borderlineReason: isBorderlineScore(borderlineScore).reason,
    result: getScoreResult(borderlineScore),
    comment: '作品整体尚可，但笔法略显生硬，结构基本合理。分数处于合格线边缘，建议复核。',
    reviewStatus: 'pending',
    reviewRecord: {
      id: 'review-1',
      scoreId: 'score-1',
      registrationId: 'reg-6',
      initialScore: borderlineScore,
      finalScore: null,
      reason: '分数处于合格线临界区间，需复核确认',
      reviewJudgeName: '',
      status: 'pending',
      createdAt: '2026-06-15T16:05:00Z',
      reviewedAt: null,
    },
    published: false,
    createdAt: '2026-06-15T16:00:00Z',
  },
  {
    id: 'score-2',
    registrationId: 'reg-7',
    sessionId: 'session-3',
    candidateName: '周九',
    appliedLevel: 3,
    judgeName: '王评委',
    score: normalScore,
    isBorderline: isBorderlineScore(normalScore).isBorderline,
    borderlineReason: isBorderlineScore(normalScore).reason,
    result: getScoreResult(normalScore),
    comment: '笔法流畅，结构匀称，整体表现良好。',
    reviewStatus: 'approved',
    reviewRecord: null,
    published: false,
    createdAt: '2026-06-15T15:00:00Z',
  },
]
